FinalProjectSeddik/Controllers/ComptitveController.cs
using FinalProjectSeddik.Data;
using FinalProjectSeddik.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectSeddik.Controllers
{
    public class ComptitveController : Controller
    {
        private AppDbContext db;
        UserManager<ApplicationUser> _userManager;
        SignInManager<ApplicationUser> _signInManager;
        public ComptitveController(AppDbContext context, UserManager<ApplicationUser> applicationUser, SignInManager<ApplicationUser> signInManager)
        {
            db = context;
            _userManager = applicationUser;
            _signInManager = signInManager;
        }

        //  صفحه ارسال المشروع

        public async Task<IActionResult> UploadProject() 
        {
            ViewBag.user = await _userManager.GetUserAsync(User);

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UploadProject(Projects model)
        {

            var user = await _userManager.GetUserAsync(User);
            var Comp = db.compRegs.Where(c => c.Email == user.Email).FirstOrDefault();
            model.Name = user.Name;
            model.Specialization = user.Specialization;
            model.Email = user.Email;
            model.CompId = Comp.Id;
            db.Projects.Add(model);
            
            db.SaveChanges();
            user.IsProjSent = true;
            await _userManager.UpdateAsync(user);
            return RedirectToAction("Index", "Home");
        }
        // نهايه صفحه ارسال المشروع

        // بروفايل ال Comptitve
        public IActionResult ComptitveProfile()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var user = db.compRegs.FirstOrDefault();

            return View(user);
        }
    }
}

FinalProjectSeddik/Views/Comptitve/ComptitveProfile.cshtml
@using Microsoft.AspNetCore.Identity
@model FinalProjectSeddik.Models.compRegs

        <div class="container">
            <div class="profile-page row">
                <div class="info row">
                    <div class="~/img-profile col-sm-12 col-lg-4 col-xl-4">
                        <img src="~/image/Profile.jpg" alt="">
                    </div>
                    <div class="info-group col-sm-12 col-lg-8 col-xl-8">
                        <div class="name">
                            <label asp-for="FullName">الاسم</label>
                            <input type="text" asp-for="FullName" id="name" disabled>
                        </div>
                        <div class="email">
                            <label asp-for="Email">البريد الالكتروني</label>
                            <input type="email" asp-for="Email" id="email" disabled>
                        </div>
                        <div class="phone">
                            <label asp-for="MobileNumber">رقم الهاتف</label>
                            <input type="text" asp-for="MobileNumber" id="phone" disabled>
                        </div>
                        <div class="National_ID">
                            <label asp-for="NationalId">الرقم القومي</label>
                            <input type="text" asp-for="NationalId" id="National_ID" disabled>
                        </div>
                        <div class="type">
                            <label asp-for="Gender">النوع</label>
                            <input type="text" asp-for="Gender" id="type" disabled>
                        </div>
                        <div class="Specialization">
                            <label asp-for="Specialization">التخصص</label>
                            <input type="text" asp-for="Specialization" id="Specialization" disabled>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    

FinalProjectSeddik/Views/Comptitve/UploadProject.cshtml
@model Projects
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style (1).css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">




</head>
<body>

    @if (ViewBag.user.IsProjSent == true)
    {
<h1 class="word-send" >
    لقد قمت بارسال مشروعك ، اذا كان هناك مشكلة يرجى ارسال رسالة لنا.
</h1> }
else
{
<form method="post" asp-action="UploadProject" asp-controller="Comptitve" class="send-project">

    

        <!--  start head of table -->

    
        <input type="url"
               id="url"
               asp-for="DriveLink"
               placeholder=" ( رابط درايف ) رابط المشروع"
               required>
    


   

    <input type="submit" name="" value="ارسال" id="login">
</form>
}

    <!-- integration wit java script -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/js/scriptA.js"></script>
    <script src="../accept requist/js.js"></script>

</body>
</html>